### ISSUE TITLE
[WTH Core] Timings

### ISSUE THREAD

**Issue by MikeWedderburn-Clarke** [microsoft/WhatTheHack#248]
Please include rough/estimated time for each hack.
This would help enormously in planning.
Planners and attendees need to know roughly how much time to expect to spend on each so we can book the time away.

**Comment by jrzyshr** [comment]
@MikeWedderburn-Clarke It's been a year since you opened this suggestion issue.  The WTH V-Team has not forgotten it. :)  We have recently updated the markdown templates our authors use to include this information in the coach's guide.  This will be requested of all authors going forward during our content review process.  

For existing hacks, it will be up to the original authors or anyone who wants to contribute what their experience is on timing to submit a PR updating the coach's guide for that hack.

For reference, here's the new Coach Guide Template: https://github.com/microsoft/WhatTheHack/blob/master/000-HowToHack/WTH-CoachGuide-Template.md

I'm going to close this issue as resolved for now.
