### ISSUE TITLE
[Request]: Issue in 002-IntroToAzureAI

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/WhatTheHack#336]
### Which Hack?

002-IntroToAzureAI

### Current Behavior

As mentioned in the instructions in [challenge 1.1 Setup.md](https://github.com/microsoft/WhatTheHack/blob/master/002-IntroToAzureAI/Student/Resources/Challenge-1.1-Computer-Vision/1_Setup.md): A repository to be cloned from `https://github.com/Azure/LearnAI-Bootcamp.git` but this repository is not available. Since, this repo contains the setup/solution files to perform the challenges.

Can you please take a look at this and suggest from where the  project solution code can be downloaded, since https://github.com/Azure/LearnAI-Bootcamp.git repo is not available.

### Expected Behavior

As mentioned in the instructions in [challenge 1.1 Setup.md](https://github.com/microsoft/WhatTheHack/blob/master/002-IntroToAzureAI/Student/Resources/Challenge-1.1-Computer-Vision/1_Setup.md): A repository to be cloned from `https://github.com/Azure/LearnAI-Bootcamp.git` but this repository is not available. Since, this repo contains the setup/solution files to perform the challenges.

Can you please take a look at this and suggest from where the  project solution code can be downloaded, since https://github.com/Azure/LearnAI-Bootcamp.git repo is not available.

Thanks,
Tejaswini 

### Steps To Reproduce

The following repository is not available.

Repository URL: https://github.com/Azure/LearnAI-Bootcamp.git

<img width="693" alt="wthissue" src="https://user-images.githubusercontent.com/52440474/152579274-0d784666-2da1-4df9-9f9c-e7c3b6cebe0b.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akn9050** [comment]
Can you please provide an update on this @gfilicetti

**Comment by jrzyshr** [comment]
Hello @akn9050 Amit!  Thanks for alerting us that the repo this hack depends on does not appear to be available.  This is one of our oldest hacks and hasn't been updated since 2018.  IIRC, it was based off of another Azure Bootcamp course, which is the repo that appears to be not available.  I will reach out to the original authors and see if they know where that content came from and if we can get access to it.   

Assuming this is older content, and the owners of the Azure Bootcamp removed their repo, then we will need to either flag this hack as being archived until/unless someone wants to volunteer to update it.
-Peter

**Comment by jrzyshr** [comment]
Closing this issue as hack 002-IntroToAI has been marked as "Archived".  We welcome contributions from the community if anyone is interested in updating the content.  Please open a new Proposal issue as per the [WTH Contribution Guide](https://aka.ms/wthcontribute) and the WTH team will help you get started!
