### ISSUE TITLE
[Bug]: FHIR Hack Using Deprecated and/or Outdated Resources 

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/WhatTheHack#403]
### Which Hack?

027-FHIRPoweredHealthcare

### Current Behavior

Hello! I'm on the FHIR team and found this resource through a bug report on our [FHIR OSS repo](https://github.com/microsoft/fhir-server/issues/2555). Love the project and I have some update suggestions to align this to our product offerings since we've had some updates.

We released Azure Health Data Services as our new, preferred FHIR offering a couple of months ago. Microsoft trainings around FHIR should all be using this new offering.

The Health Architectures site has now been deprecated. Any dependencies you need from there should be pulled into your repo and maintained. See [this repo](https://github.com/microsoft/azure-health-data-services-workshop/) for an example. 

### Expected Behavior

- Exercises use Azure Health Data Services FHIR Service, not API for FHIR
- Exercises don't use Health Architectures
- FHIR Proxy should only be used under consideration.

### Anything else?

Please let me know if you need any advisory help on this! 😄 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rsliang** [comment]
Since the FHIR ecosystem reference architectures from the  Health Architectures site leveraged in the FHIR Powered Healthcare hack have been deprecated,  its contents are currently being updated to align with hack contents in the azure-health-data-services-workshop repo.

The following are the proposed changes for WTH FHIR Powered Healthcare hack contents:
1. Ch 1 - Change FHIR ingestion architecture to the new OSS FHIR Bulk Loader ingestion pipeline.  Note: It will no longer requires AD Admin access.  
2. Challenge 2 & 3 - Change HL7 & C-CDA to FHIR conversion to use new $convert-data API operation in FHIR Service.
3. Challenge 5 - Remove (no longer deploying FHIR Server Samples architecture in the deprecated Ch 1 infrastructure)
4. Challenge 9 - Change to use new FHIR-to-Synapse analytics pipeline.  It will auto export new FHIR data as Parquet file into a ‘fhir’ Blob container and auto populate external tables and views in Synapse SQL Serverless Pool for secondary use cases.

**Comment by rsliang** [comment]
Additional changes proposed:
- Challenge 7 - Replace existing export & anonymize pipeline to use $export API operation in FHIR Service
- Challenge 8 - Replace with MedTech Services in Azure Health Data Services, and use IoT mapper tool to map sample messages.

**Comment by jrzyshr** [comment]
This issue is closed with PR #515
